#%RAML 1.0 NamedExample
orderRequestExample:
  {
    order: {
      orderHeader: {
        orderNumber: "11405042",
        orderQty : "6",
        totalCost : "3000",
        cardName: "SBI",
        operation: "Create"
      }
    }
  }